all_joints:
- - 0
- - 1
all_joints_names:
- nose
- tail
alpha_r: 0.02
apply_prob: 0.5
batch_size: 1
contrast:
  clahe: true
  claheratio: 0.5
  histeq: true
  histeqratio: 0.5
convolution:
  edge: true
  emboss:
    alpha:
    - 0.0
    - 1.0
    strength:
    - 0.5
    - 1.5
  embossratio: 0.5
  sharpen: true
  sharpenratio: 0.5
covering: true
crop_by: 0.25
cropratio: 1.0
dataset:
  training-datasets\iteration-0\UnaugmentedDataSet_FullDatasetDec12\FullDataset_CullenLab100shuffle100.mat
dataset_type: imgaug
decay_steps: 30000
display_iters: 100
elastic_transform: true
gaussian_noise: 18
global_scale: 1.0
init_weights:
  C:\Users\culle\anaconda3\envs\dlc\lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained\resnet_v1_50.ckpt
intermediate_supervision: true
intermediate_supervision_layer: 6
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
lr_init: 0.0005
max_input_size: 1920
metadataset:
  training-datasets\iteration-0\UnaugmentedDataSet_FullDatasetDec12\Documentation_data-FullDataset_100shuffle100.pickle
min_input_size: 64
mirror: false
motion_blur: true
multi_stage: false
multi_step:
- - 0.001
  - 100000
net_type: resnet_50
num_joints: 2
pairwise_huber_loss: false
pairwise_predict: false
partaffinityfield_predict: false
pos_dist_thresh: 17
project_path:
  Z:/Current-Members/Oliver/CircMouseRevision/FullDataset-CullenLab-2023-12-12
rotation: 180
rotratio: 1.0
save_iters: 10000
scale_jitter_lo: 0.25
scale_jitter_up: 1.0
